import { GoogleGenAI } from "@google/genai";
import { Photo, TemplateScene, TemplateStyle } from "../types";

// Helper to convert file to Base64
const fileToGenerativePart = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      const base64Data = base64String.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

const processImageForAI = async (photo: Photo): Promise<string> => {
  if (photo.rotation === 0) {
    return fileToGenerativePart(photo.file);
  }

  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error("Canvas context not available"));
        return;
      }

      if (photo.rotation === 90 || photo.rotation === 270) {
        canvas.width = img.height;
        canvas.height = img.width;
      } else {
        canvas.width = img.width;
        canvas.height = img.height;
      }

      ctx.translate(canvas.width / 2, canvas.height / 2);
      ctx.rotate((photo.rotation * Math.PI) / 180);
      ctx.drawImage(img, -img.width / 2, -img.height / 2);

      const dataUrl = canvas.toDataURL('image/jpeg', 0.9);
      resolve(dataUrl.split(',')[1]);
    };
    img.onerror = reject;
    img.src = photo.previewUrl;
  });
};

/**
 * Checks if the image contains a clear human face.
 */
export const detectFace = async (photo: Photo): Promise<boolean> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key is missing");

  const ai = new GoogleGenAI({ apiKey });
  const base64Image = await processImageForAI(photo);

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: base64Image
            }
          },
          { text: "Does this image contain a clear, identifiable human face? Answer with only 'yes' or 'no'." }
        ]
      }
    });

    const result = response.text?.toLowerCase().trim();
    return result === 'yes';
  } catch (error) {
    console.error("Face detection failed", error);
    return true; // Fallback to true to not block users on technical transient errors
  }
};

export const generateBabyPhoto = async (
  photo: Photo,
  scene: TemplateScene,
  style: TemplateStyle
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key is missing");

  const ai = new GoogleGenAI({ apiKey });
  const base64Image = await processImageForAI(photo);

  const prompt = `
    Generate a high-quality, realistic baby photo based on the input image.
    Keep the baby's facial features consistent with the input image.
    Scene: ${scene.promptPart}.
    Style: ${style.promptPart}.
    Aspect Ratio: 16:9.
    High resolution, detailed texture, professional photography, soft lighting.
    Ensure the baby looks adorable and the composition is balanced.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: base64Image
            }
          },
          { text: prompt }
        ]
      }
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("AI Generation Error:", error);
    throw error;
  }
};
